#!/bin/zsh

setopt COMPLETE_IN_WORD

### bling.sh source start
# test -f /usr/share/ublue-os/bluefin-cli/bling.sh && source /usr/share/ublue-os/bluefin-cli/bling.sh
### bling.sh source end

# non-bluefin, do it manually
if [ -z "$BLING_SOURCED" ]; then
    if [ "$(command -v eza)" ]; then
        alias ll='eza -l --icons=auto --group-directories-first'
        alias l.='eza -d .*'
        alias ls='eza'
        alias l1='eza -1'
    fi

    if [ "$(command -v ug)" ]; then
        alias grep='ug'
        alias egrep='ug -E'
        alias fgrep='ug -F'
        alias xzgrep='ug -z'
        alias xzegrep='ug -zE'
        alias xzfgrep='ug -zF'
    fi

    [ "$(command -v starship)" ] && eval "$(starship init zsh)"
    [ "$(command -v atuin)" ] && eval "$(atuin init zsh ${ATUIN_INIT_FLAGS})"
    [ "$(command -v zoxide)" ] && eval "$(zoxide init zsh)"
fi

# zsh history tweaks
export HISTSIZE=100000
export SAVEHIST=100000
export HISTFILE="$HOME/.zsh_history"
setopt HIST_REDUCE_BLANKS # remove leading blanks from history
setopt APPEND_HISTORY     # append to history file, don't overwrite it
setopt HIST_IGNORE_SPACE # don't enter into history if command starts with space
setopt HIST_IGNORE_DUPS  # don't enter into history if duplicate of previous command
setopt SHARE_HISTORY     # write to history file after every command, and import into other zsh instances

# zsh keybindings
autoload -U select-word-style
select-word-style bash
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # up
bindkey "^[[B" down-line-or-beginning-search # down
bindkey '^[[1;5C' emacs-forward-word # ctrl-right
bindkey '^[[1;5D' emacs-backward-word # ctrl-left
bindkey '^[f' emacs-forward-word # opt-right
bindkey '^[b' emacs-backward-word # opt-left

# all completions should be sourced after this.
autoload -Uz compinit
compinit

# zsh plugins
function brew-zsh-plugin() {
    [ -f "$HOMEBREW_PREFIX/share/$1" ] && . "$HOMEBREW_PREFIX/share/$1"
}
brew-zsh-plugin zsh-fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
brew-zsh-plugin zsh-autosuggestions/zsh-autosuggestions.zsh
brew-zsh-plugin zsh-autopair/autopair.zsh
unset -f brew-zsh-plugin
