#!/bin/bash

# common profile
if [ -f ~/.profile ]; then
    . ~/.profile
fi

# mise
command -v mise >/dev/null && eval "$(mise env --shell bash)"

# local profile
if [ -d ~/.profile.d ]; then
  for profile_file in ~/.profile.d/*; do
    if [ -f "$profile_file" ]; then
      . "$profile_file"
    fi
  done
fi
unset profile_file

# bashrc
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
