#!/bin/sh

# local bin
export PATH="$HOME/.local/bin:$HOME/bin:$PATH"

# Jetbrains
export PATH="$PATH:$HOME/.local/share/JetBrains/Toolbox/scripts"

# Claude
export PATH="$PATH:$HOME/.claude/local"

# manually installed atuin
export PATH="$HOME/.atuin/bin:$PATH"

# homebrew
case "$(uname -s)" in
Darwin)
  if [ -f /usr/local/bin/brew ]; then
    eval "$(/usr/local/bin/brew shellenv)"
  elif [ -f /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
  if [ -n "$HOMEBREW_PREFIX" ]; then
    export FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

    # gnu tooling
    GNU_PATH=$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin
    GNU_PATH=$GNU_PATH:$HOMEBREW_PREFIX/opt/gnu-sed/libexec/gnubin
    GNU_PATH=$GNU_PATH:$HOMEBREW_PREFIX/opt/gnu-tar/libexec/gnubin
    export PATH=$GNU_PATH:$PATH

    GNU_MANPATH=$HOMEBREW_PREFIX/opt/coreutils/libexec/gnuman
    GNU_MANPATH=$GNU_MANPATH:$HOMEBREW_PREFIX/opt/gnu-sed/libexec/gnuman
    GNU_MANPATH=$GNU_MANPATH:$HOMEBREW_PREFIX/opt/gnu-tar/libexec/gnuman
    export MANPATH=$GNU_MANPATH:$MANPATH

    # MoltenVK / Vulkan SDK
    if [ -d "$HOMEBREW_PREFIX/opt/molten-vk" ]; then
      export VULKAN_SDK="$HOMEBREW_PREFIX/opt/molten-vk"
    fi
  fi
  ;;
Linux)
  if [ -f /home/linuxbrew/.linuxbrew/bin/brew ]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  fi
  ;;
esac

# android
[ -d "$HOME/Library/Android/sdk" ] && {
  export ANDROID_HOME="$HOME/Library/Android/sdk"
  export PATH="$ANDROID_HOME/platform-tools:$PATH"
}

# misc env vars
export ATUIN_INIT_FLAGS='--disable-up-arrow'
export PAGER='less -RF --mouse'
export DELTA_PAGER="$PAGER"
export EDITOR='nvim'
