#!/bin/zsh

# common profile
if [ -f ~/.profile ]; then
    . ~/.profile
fi

# local profile
if [ -d ~/.profile.d ]; then
  for profile_file in ~/.profile.d/*(N); do
    if [ -f "$profile_file" ]; then
      . "$profile_file"
    fi
  done
fi
unset profile_file
