[tools]
jq = "latest"
node = "lts"
"npm:watchman" = "latest"

[settings]
lockfile = true

[tasks.apply]
description = "Apply changes manually"
run = "chezmoi apply"

[tasks.diff]
description = "Show diff between source state and destination state"
run = "chezmoi diff"
