[settings]
trusted_config_paths = ["~/Code", "~/Projects"]

[settings.python]
compile = false

[tools]
"core:go" = "latest"
"core:java" = "temurin-25"
"core:node" = "lts"
"core:python" = "latest"
"core:rust" = "latest"

"aqua:jdx/aube" = "latest"
"aqua:astral-sh/uv" = "latest"
"github:Foxboron/ssh-tpm-agent" = { version = "latest", os = ["linux"] }
"github:sargunv/starship-multi-config" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
