[settings]
trusted_config_paths = [
  "~/.local/share/chezmoi",
  "~/Code",
  "~/Projects",
  "~/.codex/worktrees",
  "~/.t3/worktrees"
]

[settings.python]
compile = false

[tools]
"core:go" = "latest"
"core:java" = "temurin-25"
"core:node" = "lts"
"core:python" = "latest"
"core:rust" = "latest"

"aqua:jdx/aube" = "latest"
"aqua:jdx/usage" = "latest"
"aqua:astral-sh/uv" = "latest"
"aqua:cargo-bins/cargo-binstall" = "latest"
"aqua:anomalyco/opencode" = "latest"
"aqua:anthropics/claude-code" = "latest"
"aqua:earendil-works/pi" = "latest"
"aqua:openai/codex" = "latest"
"github:Foxboron/ssh-tpm-agent" = { version = "latest", os = ["linux"] }
"github:can1357/oh-my-pi" = "latest"
"github:sargunv/starship-multi-config" = "latest"
"npm:@qwen-code/qwen-code" = "latest"
