[settings]
trusted_config_paths = [
  "~/.local/share/chezmoi",
  "~/Code",
  "~/Projects",
  "~/.codex/worktrees",
  "~/.t3/worktrees"
]

[settings.python]
compile = false

[tools]
"core:go" = "latest"
"core:java" = "temurin-25"
"core:node" = "lts"
"core:python" = "latest"
"core:rust" = "latest"

"aqua:jdx/aube" = "latest"
"aqua:jdx/usage" = "latest"
"aqua:astral-sh/uv" = "latest"
"aqua:cargo-bins/cargo-binstall" = "latest"
"github:Foxboron/ssh-tpm-agent" = { version = "latest", os = ["linux"] }
"github:sargunv/starship-multi-config" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
