set -g default-terminal "tmux-256color"
set -g base-index 1
setw -g pane-base-index 1

set -g status-keys vi
set -g mode-keys vi

bind-key -N "Kill the current window" & kill-window
bind-key -N "Kill the current pane" x kill-pane

set -g mouse on
set -g focus-events on
setw -g aggressive-resize on
setw -g clock-mode-style 24
set -s escape-time 0
set -g history-limit 50000

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

run-shell "$HOME/.config/tmux/plugins/tpm/tpm"
