name: ci

on:
  push:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Homebrew/actions/setup-homebrew@master
      - run: ./install.sh
      - run: chezmoi data
